// Print and PDF export utilities for FieldVibe

export function printPage(title?: string) {
  const originalTitle = document.title
  if (title) document.title = title
  window.print()
  document.title = originalTitle
}

export function generatePrintStyles(): string {
  return `
    @media print {
      body { background: white !important; color: black !important; }
      .no-print, nav, .sidebar, header, footer, .fab, .bottom-tabs { display: none !important; }
      .print-only { display: block !important; }
      .print-break { page-break-before: always; }
      .print-no-break { page-break-inside: avoid; }
      table { border-collapse: collapse; width: 100%; }
      th, td { border: 1px solid #ddd; padding: 8px; text-align: left; font-size: 12px; }
      th { background-color: #f5f5f5 !important; font-weight: bold; }
      h1, h2, h3 { page-break-after: avoid; }
      img { max-width: 100% !important; }
      a { text-decoration: none; color: black; }
      .stat-card { border: 1px solid #ddd; padding: 12px; margin: 4px; }
    }
  `
}

export interface PDFDocumentData {
  title: string
  subtitle?: string
  companyName?: string
  documentNumber?: string
  date?: string
  items?: Array<Record<string, string | number>>
  columns?: string[]
  totals?: Record<string, string | number>
  notes?: string
  footer?: string
}

export function generateInvoicePDF(data: PDFDocumentData): void {
  const printWindow = window.open('', '_blank')
  if (!printWindow) return

  const itemRows = (data.items || []).map(item => {
    return `<tr>${(data.columns || Object.keys(item)).map(col =>
      `<td style="border:1px solid #ddd;padding:8px;text-align:left">${item[col] ?? ''}</td>`
    ).join('')}</tr>`
  }).join('')

  const totalRows = data.totals ? Object.entries(data.totals).map(([label, value]) =>
    `<tr><td colspan="${(data.columns || []).length - 1}" style="border:1px solid #ddd;padding:8px;text-align:right;font-weight:bold">${label}</td><td style="border:1px solid #ddd;padding:8px;font-weight:bold">${value}</td></tr>`
  ).join('') : ''

  const html = `<!DOCTYPE html>
<html><head>
<title>${data.title}</title>
<style>
  body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
  .header { display: flex; justify-content: space-between; align-items: start; margin-bottom: 30px; border-bottom: 2px solid #2563eb; padding-bottom: 20px; }
  .company { font-size: 24px; font-weight: bold; color: #2563eb; }
  .doc-info { text-align: right; }
  .doc-number { font-size: 18px; font-weight: bold; }
  .doc-date { color: #666; margin-top: 4px; }
  table { width: 100%; border-collapse: collapse; margin: 20px 0; }
  th { background: #f1f5f9; border: 1px solid #ddd; padding: 10px 8px; text-align: left; font-weight: 600; font-size: 13px; }
  td { border: 1px solid #ddd; padding: 8px; font-size: 13px; }
  .notes { margin-top: 30px; padding: 15px; background: #f9fafb; border-radius: 8px; }
  .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #999; border-top: 1px solid #eee; padding-top: 15px; }
  @media print { body { margin: 20px; } }
</style>
</head><body>
<div class="header">
  <div>
    <div class="company">${data.companyName || 'FieldVibe'}</div>
    <div style="color:#666;margin-top:4px">${data.subtitle || ''}</div>
  </div>
  <div class="doc-info">
    <div class="doc-number">${data.title} ${data.documentNumber || ''}</div>
    <div class="doc-date">${data.date || new Date().toLocaleDateString()}</div>
  </div>
</div>
${data.items && data.items.length > 0 ? `
<table>
  <thead><tr>${(data.columns || Object.keys(data.items[0])).map(col =>
    `<th>${col}</th>`
  ).join('')}</tr></thead>
  <tbody>${itemRows}${totalRows}</tbody>
</table>` : ''}
${data.notes ? `<div class="notes"><strong>Notes:</strong> ${data.notes}</div>` : ''}
<div class="footer">${data.footer || 'Generated by FieldVibe - ' + new Date().toLocaleString()}</div>
</body></html>`

  printWindow.document.write(html)
  printWindow.document.close()
  setTimeout(() => {
    printWindow.print()
  }, 500)
}

export function exportToCSV(data: Record<string, unknown>[], filename: string) {
  if (!data.length) return
  const headers = Object.keys(data[0])
  const csvContent = [
    headers.join(','),
    ...data.map(row => headers.map(h => {
      const val = String(row[h] ?? '')
      return val.includes(',') || val.includes('"') || val.includes('\n')
        ? `"${val.replace(/"/g, '""')}"` : val
    }).join(','))
  ].join('\n')

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = `${filename}-${Date.now()}.csv`
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
